<?php

function cablecast_media_node_presave($node) {
	if($node->type == 'cablecast_show') {

    // We only want to get the image if it doesn't already exist
    // This way a user can replace the image after the show is created.
    if(isset($node->cablecast_show_thumbnail) &&
       $node->cablecast_show_thumbnail['und'][0]['fid'] > 0) {
      return;
    }

		try {
      //Check if directory is writeable
      $cablecast_media_files = 'public://cablecast';
      $writable = file_prepare_directory($cablecast_media_files);

      if($writable == false) {
        watchdog('Cablecast Media', 'Cablecast Files is not writeable', NULL, WATCHDOG_ERROR);
        return;
      }

      $cablecast_server_uri = variable_get('cablecast_server_url', 0);
      $show_id = $node->cablecast_show_id['und'][0]['value'];

      // TODO we could also search for user uploaded files.
      $thumbnail_url = $cablecast_server_uri . 
                              "/Cablecast/ShowFiles/" . 
                              $show_id . 
                              "/_thumbnail-1.png";

      $response = drupal_http_request($thumbnail_url, array('method' => 'HEAD'));
      $file_exists = $response->code == '404' ? false : true;

      if($file_exists) {
        // TODO its possible the image isn't a png
        $destination = 'public://cablecast/' . $show_id . '.png';

        $file = system_retrieve_file($thumbnail_url, $destination, TRUE);
        
        if($file->fid > 0) {
          $node->cablecast_show_thumbnail['und'][0]['fid'] = $file->fid;
        }
      }

    } catch (Exception $e) {
      //Just don't do anything
    }
	}
}